version: "3.8"

services:
  anime-app:
    container_name: anime-list-app
    build: .
    expose:
      - "3001"
    env_file:
      - .env.local
    environment:
      - PORT=3001
    restart: unless-stopped
    networks:
      - anime-network
